### ISSUE TITLE
BEMify all the things

### ISSUE THREAD

**Issue by SiAdcock** [WDOTS/wdots.github.io#68]
[BEM](http://getbem.com/) makes our styles easier to understand, reduces the amount of code we have to maintain and also reduces the page weight. It makes it easier to think of class names and keeps our CSS notation more consistent. It reduces nesting, which improves the render speed of our page.

- [ ] [components/add-to-calendar](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_add-to-calendar.scss)
- [x] [components/button](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_button.scss)
- [ ] [components/container](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_container.scss)
- [x] [components/feature](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_feature.scss): Fixed in #84
- [x] [components/icon](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_icon.scss): Fixed in #84
- [x] [components/reason](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_reason.scss): Fixed in #84
- [x] [components/section](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_section.scss): Fixed in #84
- [x] [components/side-menu](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/components/_side-menu.scss): Fixed in #84
- [x] [modules/footer](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/modules/_footer.scss): Fixed in #84
- [x] [modules/hero-header](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/modules/_hero-header.scss): Fixed in #84
- [x] [modules/next-meetup](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/modules/_next-meetup.scss): Fixed in #67 
- [x] [modules/speakers](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/modules/_speakers.scss): Fixed in #84 
- [x] [modules/tickets](https://github.com/WDOTS/wdots.github.io/blob/integration/src/css/modules/_tickets.scss): Fixed in #84

**Comment by SiAdcock** [comment]
It's probably not possible to BEMify the `add-to-calendar` styles without making changes to `add-to-calendar` itself. I think we're BEM enough to close this issue now.
